#!/usr/bin/env node

/**************************************************************************************************
 * Imports
 **************************************************************************************************/

var chalk   = require("chalk"),
    fs      = require("fs"),
    path    = require("path"),
    program = require("commander"),
    shell   = require("shelljs");


/**************************************************************************************************
 * Variables
 *************************************************************************************************/

var colors = {
        error:   chalk.bold.red,
        success: chalk.bold.green,
        warning: chalk.keyword("orange"),
    },
    version = "0.0.2";


/**************************************************************************************************
 * Functions
 *************************************************************************************************/

var ops = {
    echo(message, padTop, padBottom) {
        padBottom = padBottom === true;
        padTop    = padTop    === true;

        if (padTop) { this.echoNewline(); }
        shell.echo(message);
        if (padBottom) { this.echoNewline(); }
    },

    echoError(message, padTop, padBottom, prefix) {
        prefix = prefix === undefined || prefix === null ? "Error: " : prefix + " ";
        this.echo(colors.error(prefix + message), padTop, padBottom);
    },

    echoDivider() {
        shell.echo("---------------------------------------------------------------------------------");
    },

    echoHeader(name) {
        this.echoNewline();
        this.echoDivider();
        this.echo(name, true, true);
        this.echoDivider();
        this.echoNewline();
    },

    echoNewline(count) {
        count = count === undefined || count === null ? 1 : count;
        for (var i = 1; i <= count; i ++) {
            shell.echo(" ");
        }
    },

    echoWarning(message, padTop, padBottom) {
        this.echo(colors.warning("Warning: " + message), padTop, padBottom);
    },

    echoSuccess(message, padTop, padBottom) {
        this.echo(colors.success(message), padTop, padBottom);
    },

    env(name) {
        return shell.env[name];
    },

    exec(command, isSilent) {
        return shell.exec(command, { silent: isSilent === true });
    },
};

var dotnet = {

    build() {
        if (ops.exec("dotnet build").code !== 0) {
            ops.echoError("Failed to build dotnet");
            shell.exit(1);
        }
    },

    test() {
        if (ops.exec("dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover").code !== 0) {
            ops.echoError("Dotnet tests failed");
            shell.exit(1);
        }

        if (ops.exec("reportgenerator -reports:test/**/coverage.opencover.xml -targetDir:coverage").code !== 0) {
            ops.echoError("Failed to generate coverage report");
            shell.exit(1);
        }
    },
};


/**************************************************************************************************
 * Application Configuration
 **************************************************************************************************/

program
    .version(version)
    .usage("[options]")
    .option("-b, --build", "Simple wrapper to build dotnet")
    .option("-t, --test",  "Run tests along with coverage")
    .parse(process.argv);


/**************************************************************************************************
 * Init
 **************************************************************************************************/

if (program.build) {
    dotnet.build();
    shell.exit(0);
}

if (program.test) {
    // Install report generator global tool if not installed
    if (!shell.which("reportgenerator")) {
        ops.exec("dotnet tool install --global dotnet-reportgenerator-globaltool");
        ops.echoSuccess("Installed dotnet reportgenerator global tool");
    }

    dotnet.test();
    shell.exit(0);
}

// Default
program.outputHelp();
shell.exit(0);