namespace AndcultureCode.CSharp.Core.Constants
{
    /// <summary>
    /// RFC-4646 Language Codes
    /// See https://docs.microsoft.com/en-us/previous-versions/commerce-server/ee825488(v=cs.20)?redirectedfrom=MSDN
    /// </summary>
    public static class Rfc4646LanguageCodes
    {
        public const string AF_ZA = "af-ZA"; // Afrikaans - South Africa
        public const string SQ_AL = "sq-AL"; // Albanian - Albania
        public const string AR_DZ = "ar-DZ"; // Arabic - Algeria
        public const string AR_BH = "ar-BH"; // Arabic - Bahrain
        public const string AR_EG = "ar-EG"; // Arabic - Egypt
        public const string AR_IQ = "ar-IQ"; // Arabic - Iraq
        public const string AR_JO = "ar-JO"; // Arabic - Jordan
        public const string AR_KW = "ar-KW"; // Arabic - Kuwait
        public const string AR_LB = "ar-LB"; // Arabic - Lebanon
        public const string AR_LY = "ar-LY"; // Arabic - Libya
        public const string AR_MA = "ar-MA"; // Arabic - Morocco
        public const string AR_OM = "ar-OM"; // Arabic - Oman
        public const string AR_QA = "ar-QA"; // Arabic - Qatar
        public const string AR_SA = "ar-SA"; // Arabic - Saudi Arabia
        public const string AR_SY = "ar-SY"; // Arabic - Syria
        public const string AR_TN = "ar-TN"; // Arabic - Tunisia
        public const string AR_AE = "ar-AE"; // Arabic - United Arab Emirates
        public const string AR_YE = "ar-YE"; // Arabic - Yemen
        public const string HY_AM = "hy-AM"; // Armenian - Armenia
        public const string CY_AZ_AZ = "Cy-az-AZ"; // Azeri (Cyrillic) - Azerbaijan
        public const string LT_AZ_AZ = "Lt-az-AZ"; // Azeri (Latin) - Azerbaijan
        public const string EU_ES = "eu-ES"; // Basque - Basque
        public const string BE_BY = "be-BY"; // Belarusian - Belarus
        public const string BG_BG = "bg-BG"; // Bulgarian - Bulgaria
        public const string CA_ES = "ca-ES"; // Catalan - Catalan
        public const string ZH_CN = "zh-CN"; // Chinese - China
        public const string ZH_HK = "zh-HK"; // Chinese - Hong Kong SAR
        public const string ZH_MO = "zh-MO"; // Chinese - Macau SAR
        public const string ZH_SG = "zh-SG"; // Chinese - Singapore
        public const string ZH_TW = "zh-TW"; // Chinese - Taiwan
        public const string ZH_CHS = "zh-CHS"; // Chinese (Simplified)
        public const string ZH_CHT = "zh-CHT"; // Chinese (Traditional)
        public const string HR_HR = "hr-HR"; // Croatian - Croatia
        public const string CS_CZ = "cs-CZ"; // Czech - Czech Republic
        public const string DA_DK = "da-DK"; // Danish - Denmark
        public const string DIV_MV = "div-MV"; // Dhivehi - Maldives
        public const string NL_BE = "nl-BE"; // Dutch - Belgium
        public const string NL_NL = "nl-NL"; // Dutch - The Netherlands
        public const string EN_AU = "en-AU"; // English - Australia
        public const string EN_BZ = "en-BZ"; // English - Belize
        public const string EN_CA = "en-CA"; // English - Canada
        public const string EN_CB = "en-CB"; // English - Caribbean
        public const string EN_IE = "en-IE"; // English - Ireland
        public const string EN_JM = "en-JM"; // English - Jamaica
        public const string EN_NZ = "en-NZ"; // English - New Zealand
        public const string EN_PH = "en-PH"; // English - Philippines
        public const string EN_ZA = "en-ZA"; // English - South Africa
        public const string EN_TT = "en-TT"; // English - Trinidad and Tobago
        public const string EN_GB = "en-GB"; // English - United Kingdom
        public const string EN_US = "en-US"; // English - United States
        public const string EN_ZW = "en-ZW"; // English - Zimbabwe
        public const string ET_EE = "et-EE"; // Estonian - Estonia
        public const string FO_FO = "fo-FO"; // Faroese - Faroe Islands
        public const string FA_IR = "fa-IR"; // Farsi - Iran
        public const string FI_FI = "fi-FI"; // Finnish - Finland
        public const string FR_BE = "fr-BE"; // French - Belgium
        public const string FR_CA = "fr-CA"; // French - Canada
        public const string FR_FR = "fr-FR"; // French - France
        public const string FR_LU = "fr-LU"; // French - Luxembourg
        public const string FR_MC = "fr-MC"; // French - Monaco
        public const string FR_CH = "fr-CH"; // French - Switzerland
        public const string GL_ES = "gl-ES"; // Galician - Galician
        public const string KA_GE = "ka-GE"; // Georgian - Georgia
        public const string DE_AT = "de-AT"; // German - Austria
        public const string DE_DE = "de-DE"; // German - Germany
        public const string DE_LI = "de-LI"; // German - Liechtenstein
        public const string DE_LU = "de-LU"; // German - Luxembourg
        public const string DE_CH = "de-CH"; // German - Switzerland
        public const string EL_GR = "el-GR"; // Greek - Greece
        public const string GU_IN = "gu-IN"; // Gujarati - India
        public const string HE_IL = "he-IL"; // Hebrew - Israel
        public const string HI_IN = "hi-IN"; // Hindi - India
        public const string HU_HU = "hu-HU"; // Hungarian - Hungary
        public const string IS_IS = "is-IS"; // Icelandic - Iceland
        public const string ID_ID = "id-ID"; // Indonesian - Indonesia
        public const string IT_IT = "it-IT"; // Italian - Italy
        public const string IT_CH = "it-CH"; // Italian - Switzerland
        public const string JA_JP = "ja-JP"; // Japanese - Japan
        public const string KN_IN = "kn-IN"; // Kannada - India
        public const string KK_KZ = "kk-KZ"; // Kazakh - Kazakhstan
        public const string KOK_IN = "kok-IN"; // Konkani - India
        public const string KO_KR = "ko-KR"; // Korean - Korea
        public const string KY_KZ = "ky-KZ"; // Kyrgyz - Kazakhstan
        public const string LV_LV = "lv-LV"; // Latvian - Latvia
        public const string LT_LT = "lt-LT"; // Lithuanian - Lithuania
        public const string MK_MK = "mk-MK"; // Macedonian (FYROM)
        public const string MS_BN = "ms-BN"; // Malay - Brunei
        public const string MS_MY = "ms-MY"; // Malay - Malaysia
        public const string MR_IN = "mr-IN"; // Marathi - India
        public const string MN_MN = "mn-MN"; // Mongolian - Mongolia
        public const string NB_NO = "nb-NO"; // Norwegian (Bokmål) - Norway
        public const string NN_NO = "nn-NO"; // Norwegian (Nynorsk) - Norway
        public const string PL_PL = "pl-PL"; // Polish - Poland
        public const string PT_BR = "pt-BR"; // Portuguese - Brazil
        public const string PT_PT = "pt-PT"; // Portuguese - Portugal
        public const string PA_IN = "pa-IN"; // Punjabi - India
        public const string RO_RO = "ro-RO"; // Romanian - Romania
        public const string RU_RU = "ru-RU"; // Russian - Russia
        public const string SA_IN = "sa-IN"; // Sanskrit - India
        public const string CY_SR_SP = "Cy-sr-SP"; // Serbian (Cyrillic) - Serbia
        public const string LT_SR_SP = "Lt-sr-SP"; // Serbian (Latin) - Serbia
        public const string SK_SK = "sk-SK"; // Slovak - Slovakia
        public const string SL_SI = "sl-SI"; // Slovenian - Slovenia
        public const string ES_AR = "es-AR"; // Spanish - Argentina
        public const string ES_BO = "es-BO"; // Spanish - Bolivia
        public const string ES_CL = "es-CL"; // Spanish - Chile
        public const string ES_CO = "es-CO"; // Spanish - Colombia
        public const string ES_CR = "es-CR"; // Spanish - Costa Rica
        public const string ES_DO = "es-DO"; // Spanish - Dominican Republic
        public const string ES_EC = "es-EC"; // Spanish - Ecuador
        public const string ES_SV = "es-SV"; // Spanish - El Salvador
        public const string ES_GT = "es-GT"; // Spanish - Guatemala
        public const string ES_HN = "es-HN"; // Spanish - Honduras
        public const string ES_MX = "es-MX"; // Spanish - Mexico
        public const string ES_NI = "es-NI"; // Spanish - Nicaragua
        public const string ES_PA = "es-PA"; // Spanish - Panama
        public const string ES_PY = "es-PY"; // Spanish - Paraguay
        public const string ES_PE = "es-PE"; // Spanish - Peru
        public const string ES_PR = "es-PR"; // Spanish - Puerto Rico
        public const string ES_ES = "es-ES"; // Spanish - Spain
        public const string ES_UY = "es-UY"; // Spanish - Uruguay
        public const string ES_VE = "es-VE"; // Spanish - Venezuela
        public const string SW_KE = "sw-KE"; // Swahili - Kenya
        public const string SV_FI = "sv-FI"; // Swedish - Finland
        public const string SV_SE = "sv-SE"; // Swedish - Sweden
        public const string SYR_SY = "syr-SY"; // Syriac - Syria
        public const string TA_IN = "ta-IN"; // Tamil - India
        public const string TT_RU = "tt-RU"; // Tatar - Russia
        public const string TE_IN = "te-IN"; // Telugu - India
        public const string TH_TH = "th-TH"; // Thai - Thailand
        public const string TR_TR = "tr-TR"; // Turkish - Turkey
        public const string UK_UA = "uk-UA"; // Ukrainian - Ukraine
        public const string UR_PK = "ur-PK"; // Urdu - Pakistan
        public const string CY_UZ_UZ = "Cy-uz-UZ"; // Uzbek (Cyrillic) - Uzbekistan
        public const string LT_UZ_UZ = "Lt-uz-UZ"; // Uzbek (Latin) - Uzbekistan
        public const string VI_VN = "vi-VN"; // Vietnamese - Vietnam
    }
}